### ISSUE TITLE
Nommage des fonctions

### ISSUE THREAD

**Issue by brunoilponseisae** [valentinWasq/tournois-valentin-wasquel#1]
Par convention:

On écrit  
- `__str__` au lieu de `toString`
- `matchSet` au lieu de `Match_set`

dans tous les cas il faut garder de la cohérence entre le snake_case et le camelCase: https://www.theserverside.com/answer/Camel-case-vs-snake-case-Whats-the-difference

**Comment by zerustu** [comment]
j'ai corriger cela dans le commit d0f75e5
merci
